### ISSUE TITLE
Issue when trying to flash

### ISSUE THREAD

**Issue by fugitive101** [Prokuon/watchy-starfield#5]
I am facing the following error when trying to flash via IDE:

In file included from C:\Arduino\watchy-starfield-main\Star_field\Star_field.ino:1:
C:\Arduino\watchy-starfield-main\Star_field\Watchy_7_SEG.h:4:10: fatal error: Watchy.h: No such file or directory
    4 | #include <Watchy.h>
      |          ^~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: Watchy.h: No such file or directory

Any help is appreciated.

**Comment by Tmow33** [comment]
you need to install watchy library from sqmfi... but if you do you will realize that this code is over a year old and doesn't work with version 1.4.14 and then you'll get a whole new bunch of errors due to the watchy library renaming the buttons... this watch face is out dated and hasn't worked very well for months due to the watchy code updating but this stagnating. And the writer never bothered to write the version of watchy he wrote this for but i think it somewhere around version 1.4.5 or 6 but i still can't get it to work due to the broken ntp/wifi/weather/buttons/and compilation errors

**Comment by Tmow33** [comment]
you need to add the extension Watchy Sqfmi. I did end up getting it working with the new version of watchy. 1.4.14 on ArduinoIDE
